version: '3.8'
services:
  redis:
    image: redis:alpine
    container_name: wakapadi_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    restart: unless-stopped

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_URI=mongodb://mongodb:27017/wakapadi
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:5
    container_name: wakapadi_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 2s
      timeout: 5s
      retries: 30
    restart: unless-stopped

volumes:
  redis_data:
  mongo_data: